name: Docker Image Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build -t ${{ github.repository }} .
    - name: Save docker image
      run: docker save -o image.tar ${{ github.repository }}
    - name: Persist docker image
      uses: actions/upload-artifact@v1
      with:
        name: image.tar
        path: image.tar
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v1
        with:
          name: image.tar
      - name: Load docker image
        run: docker load -i image.tar
      - name: Remove docker image file
        run: rm image.tar
      - uses: actions/checkout@v1
      - name: Build test docker image
        run: docker build --build-arg BASEIMAGE=${{ github.repository }} -t ${{ github.repository }}-test test/
      - name: Run test docker image
        run: docker run --rm ${{ github.repository }}-test
  publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Login to docker registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Download docker image
        uses: actions/download-artifact@v1
        with:
          name: image.tar
      - name: Load docker image
        run: docker load -i image.tar
      - name: Publish docker image to registry
        run: docker push ${{ github.repository }}

