name: Test docker image

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: Build test docker image
        run: docker build --build-arg BASEIMAGE=${{ github.repository }} -t ${{ github.repository }}-test test/
      - name: Run test docker image
        run: docker run --rm ${{ github.repository }}-test

